export const FETCH_COMPETITION_BEGIN = 'FETCH_COMPETITION_BEGIN';
export const FETCH_COMPETITION_SUCCESS = 'FETCH_COMPETITION_SUCCESS';
export const FETCH_COMPETITION_ERROR = 'FETCH_COMPETITION_ERROR';